### ISSUE TITLE
Tap and hold do nothing

### ISSUE THREAD

**Issue by HritwikSinghal** [iberianpig/fusuma-plugin-tap#13]
Distribution: Manjaro 20.2 Nibia, Wayland, Gnome.

my config;
```
swipe:
  3:
    left:
      sendkey: "LEFTALT+RIGHT" # history back
      keypress:
        LEFTCTRL:
          sendkey: "PREVIOUSSONG"
        # LEFTMETA+LEFTALT:
          # sendkey: 'BRIGHTNESSDOWN'

    right:
      sendkey: "LEFTALT+LEFT" # history forward
      keypress:
        LEFTCTRL:
          sendkey: "NEXTSONG"
        # LEFTMETA+LEFTALT:
        #   sendkey: 'xdotool key --clearmodifiers XF86AudioLowerVolume'

    up:
      sendkey: "LEFTMETA" # Overview
      keypress:
        LEFTCTRL:
          sendkey: "LEFTCTRL+K" # open new tab
        LEFTCTRL+LEFTALT:
          sendkey: 'BRIGHTNESSUP'

    down:
      sendkey: "LEFTMETA" # Overview
      keypress:
        LEFTCTRL:
          sendkey: "LEFTCTRL+COMMA" # close tab
        LEFTCTRL+LEFTALT:
          sendkey: 'BRIGHTNESSDOWN'

  4:
    left:
      sendkey: "VOLUMEDOWN"
    right:
      sendkey: "VOLUMEUP"
#     up:
#       sendkey: "xdotool key ctrl+alt+Down" # Switch to next workspace
#     down:
#       sendkey: "xdotool key ctrl+alt+Up" # Switch to previous workspace
pinch:
  in:
    sendkey: "ZOOMOUT" # Zoom in
  out:
    sendkey: "ZOOMIN" # Zoom out


threshold:
  pinch: 0.4
  swipe: 0.2

interval:
  swipe: 0.8
  pinch: 0.5
  tap: 0.2

tap:
1:
  sendkey: "echo ----------------tap1----------------------------"
  # 2:
  #   sendkey: "echo ----------------tap2----------------------------"
  # 3:
    # sendkey: "echo ----------------tap3----------------------------"
  # 4:
    # sendkey: "PLAYPAUSE"

hold:
#   1:
#     command: "echo ----------------hold1----------------------------"
#   2:
#     command: "echo ----------------hold2----------------------------"
#   3:
#     command: "echo ----------------hold3----------------------------"
  4:
    sendkey: "PLAYPAUSE"

plugin:
  inputs:
    libinput_command_input:
      enable-tap: true
      verbose: true
      show-keycodes: true

```

Details of fusuma
```
    ~  fusuma                                                                                                             ✔ 
I, [2021-03-21T05:46:22.426018 #81200]  INFO -- : reload config: /home/hritwik/.config/fusuma/config.yml
I, [2021-03-21T05:46:22.474143 #81200]  INFO -- : ---------------------------------------------
I, [2021-03-21T05:46:22.474180 #81200]  INFO -- : Fusuma: 1.11.1
I, [2021-03-21T05:46:22.475746 #81200]  INFO -- : libinput: 1.17.0
I, [2021-03-21T05:46:22.476284 #81200]  INFO -- : OS: Linux 5.11.6-1-MANJARO #1 SMP PREEMPT Thu Mar 11 19:05:51 UTC 2021
I, [2021-03-21T05:46:22.476807 #81200]  INFO -- : Distribution: Manjaro Linux \r  (\n) (\l)
I, [2021-03-21T05:46:22.479360 #81200]  INFO -- : Desktop session: gnome wayland
I, [2021-03-21T05:46:22.479387 #81200]  INFO -- : ---------------------------------------------
I, [2021-03-21T05:46:22.479399 #81200]  INFO -- : Enabled Plugins: 
I, [2021-03-21T05:46:22.479460 #81200]  INFO -- :   Fusuma::Plugin::Buffers::GestureBuffer
I, [2021-03-21T05:46:22.479473 #81200]  INFO -- :   Fusuma::Plugin::Buffers::KeypressBuffer
I, [2021-03-21T05:46:22.479482 #81200]  INFO -- :   Fusuma::Plugin::Buffers::TapBuffer
I, [2021-03-21T05:46:22.479490 #81200]  INFO -- :   Fusuma::Plugin::Detectors::KeypressDetector
I, [2021-03-21T05:46:22.479498 #81200]  INFO -- :   Fusuma::Plugin::Detectors::PinchDetector
I, [2021-03-21T05:46:22.479506 #81200]  INFO -- :   Fusuma::Plugin::Detectors::RotateDetector
I, [2021-03-21T05:46:22.479513 #81200]  INFO -- :   Fusuma::Plugin::Detectors::SwipeDetector
I, [2021-03-21T05:46:22.479524 #81200]  INFO -- :   Fusuma::Plugin::Detectors::TapDetector
I, [2021-03-21T05:46:22.479536 #81200]  INFO -- :   Fusuma::Plugin::Events::Records::GestureRecord
I, [2021-03-21T05:46:22.479544 #81200]  INFO -- :   Fusuma::Plugin::Events::Records::IndexRecord
I, [2021-03-21T05:46:22.479552 #81200]  INFO -- :   Fusuma::Plugin::Events::Records::KeypressRecord
I, [2021-03-21T05:46:22.479560 #81200]  INFO -- :   Fusuma::Plugin::Events::Records::TextRecord
I, [2021-03-21T05:46:22.479568 #81200]  INFO -- :   Fusuma::Plugin::Executors::CommandExecutor
I, [2021-03-21T05:46:22.479576 #81200]  INFO -- :   Fusuma::Plugin::Executors::SendkeyExecutor
I, [2021-03-21T05:46:22.479585 #81200]  INFO -- :   Fusuma::Plugin::Executors::WmctrlExecutor
I, [2021-03-21T05:46:22.479594 #81200]  INFO -- :   Fusuma::Plugin::Filters::KeypressFilter
I, [2021-03-21T05:46:22.479603 #81200]  INFO -- :   Fusuma::Plugin::Filters::LibinputDeviceFilter
I, [2021-03-21T05:46:22.479611 #81200]  INFO -- :   Fusuma::Plugin::Filters::LibinputTimeoutFilter
I, [2021-03-21T05:46:22.479620 #81200]  INFO -- :   Fusuma::Plugin::Inputs::LibinputCommandInput
I, [2021-03-21T05:46:22.479629 #81200]  INFO -- :   Fusuma::Plugin::Parsers::KeypressParser
I, [2021-03-21T05:46:22.479638 #81200]  INFO -- :   Fusuma::Plugin::Parsers::LibinputGestureParser
I, [2021-03-21T05:46:22.479647 #81200]  INFO -- :   Fusuma::Plugin::Parsers::TapParser
I, [2021-03-21T05:46:22.479657 #81200]  INFO -- : ---------------------------------------------

```
Nothing happens when i tap with 1 finger or hold with 4 finger. I cant debug it since i dont see any log messages.
